# Create EMPS table for demo

CREATE TABLE "GARY"."EMPS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(100), 
	"PHONE" VARCHAR2(20), 
	"ADDRESS" VARCHAR2(400), 
	"CITY" VARCHAR2(200), 
	"STATE" VARCHAR2(20), 
	"ZIP" VARCHAR2(20)
   );